KERNEL_SOURCES += $(get_makefile_dir)/boot/init.S                            \
                  $(get_makefile_dir)/asm/exceptions.S

CFLAGS += -I$(get_makefile_dir)/$(BOARD)/
CFLAGS += -I$(get_makefile_dir)/include
